name: oktoast
description: A pure flutter toast library  Support custom style/widget. Easy to use. You can use this library to achieve the same effect as Android toast.
email: cjl_spy@163.com
homepage: https://github.com/OpenFlutter/flutter_oktoast
version: 3.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
